definitions:
  helper.Response:
    properties:
      data: {}
      error:
        type: string
      message_en:
        type: string
      message_vi:
        type: string
      success:
        type: boolean
    type: object
  schemas.GenerateOTPRequest:
    properties:
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
    required:
    - phone_number
    type: object
  schemas.GenerateOTPResponse:
    properties:
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
      user_id:
        type: string
    required:
    - phone_number
    - user_id
    type: object
  schemas.LoginWithOAuthRequest:
    properties:
      email:
        maxLength: 256
        minLength: 3
        type: string
    required:
    - email
    type: object
  schemas.LoginWithOAuthResponse:
    properties:
      email:
        maxLength: 256
        minLength: 3
        type: string
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
      user_id:
        type: string
    required:
    - email
    - phone_number
    - user_id
    type: object
  schemas.RegisterOAuthRequest:
    properties:
      email:
        maxLength: 256
        type: string
      full_name:
        maxLength: 256
        minLength: 3
        type: string
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
    required:
    - email
    - full_name
    - phone_number
    type: object
  schemas.RegisterOAuthResponse:
    properties:
      email:
        maxLength: 256
        type: string
      full_name:
        maxLength: 256
        minLength: 3
        type: string
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
      user_id:
        type: string
    required:
    - email
    - full_name
    - phone_number
    - user_id
    type: object
  schemas.RegisterUserRequest:
    properties:
      full_name:
        maxLength: 256
        minLength: 3
        type: string
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
    required:
    - full_name
    - phone_number
    type: object
  schemas.RegisterUserResponse:
    properties:
      full_name:
        maxLength: 256
        minLength: 3
        type: string
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
      user_id:
        type: string
    required:
    - full_name
    - phone_number
    - user_id
    type: object
  schemas.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      is_activated:
        type: boolean
      is_verified:
        type: boolean
      phone_number:
        type: string
      role:
        type: string
      updated_at:
        type: string
    required:
    - id
    type: object
  schemas.VerifyCCCDResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/schemas.UserResponse'
    required:
    - access_token
    - refresh_token
    - user
    type: object
  schemas.VerifyLoginOTPRequest:
    properties:
      otp:
        maxLength: 6
        minLength: 6
        type: string
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
      user_id:
        type: string
    required:
    - otp
    - phone_number
    - user_id
    type: object
  schemas.VerifyLoginOTPResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/schemas.UserResponse'
    required:
    - access_token
    - refresh_token
    - user
    type: object
  schemas.VerifyRegisterOTPRequest:
    properties:
      otp:
        maxLength: 6
        minLength: 6
        type: string
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
      user_id:
        type: string
    required:
    - otp
    - phone_number
    - user_id
    type: object
  schemas.VerifyRegisterOTPResponse:
    properties:
      full_name:
        maxLength: 256
        minLength: 3
        type: string
      is_activated:
        type: boolean
      phone_number:
        maxLength: 11
        minLength: 9
        type: string
      user_id:
        type: string
    required:
    - full_name
    - is_activated
    - phone_number
    - user_id
    type: object
info:
  contact: {}
paths:
  /auth/login-oauth:
    post:
      consumes:
      - application/json
      description: Authenticates a user using OAuth2 and sends an OTP to their phone
        number
      parameters:
      - description: OAuth2 login details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.LoginWithOAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent successfully
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/schemas.LoginWithOAuthResponse'
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/helper.Response'
        "404":
          description: User does not exist
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Login with OAuth2
      tags:
      - auth
  /auth/login-phone:
    post:
      consumes:
      - application/json
      description: Initiates login process by sending OTP to the provided phone number
      parameters:
      - description: Phone number for login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.GenerateOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent successfully
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/schemas.GenerateOTPResponse'
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/helper.Response'
        "404":
          description: User does not exist
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Login with phone number
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Starts the registration process by sending an OTP and creating
        a user account
      parameters:
      - description: Registration request containing phone number and full name
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User created and OTP sent successfully
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/schemas.RegisterUserResponse'
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/helper.Response'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Initiate user registration
      tags:
      - auth
  /auth/register-oauth:
    post:
      consumes:
      - application/json
      description: Register a new user using OAuth2 with Firebase authentication
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.RegisterOAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent successfully
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/schemas.RegisterOAuthResponse'
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/helper.Response'
        "409":
          description: User or email already exists
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Register a new user using OAuth2
      tags:
      - auth
  /auth/resend-otp:
    post:
      consumes:
      - application/json
      description: Resends the OTP to the provided phone number
      parameters:
      - description: OTP resend request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.GenerateOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent successfully
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/schemas.GenerateOTPResponse'
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Resend OTP
      tags:
      - auth
  /auth/verify-cccd:
    post:
      consumes:
      - multipart/form-data
      description: Verifies the front and back images of a user's CCCD, saves the
        information, and updates user status
      parameters:
      - description: Front image of CCCD
        in: formData
        name: front_image
        required: true
        type: file
      - description: Back image of CCCD
        in: formData
        name: back_image
        required: true
        type: file
      - description: User ID (UUID format)
        in: formData
        name: user_id
        required: true
        type: string
      - description: User's phone number (9-11 digits)
        in: formData
        maxLength: 11
        minLength: 9
        name: phone_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: CCCD verified successfully
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/schemas.VerifyCCCDResponse'
              type: object
        "400":
          description: Invalid request or CCCD info
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Verify user's CCCD
      tags:
      - auth
  /auth/verify-login-otp:
    post:
      consumes:
      - application/json
      description: Verifies the OTP for login, creates a user session, and returns
        user info with access and refresh tokens
      parameters:
      - description: OTP verification details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.VerifyLoginOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP verified successfully
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/schemas.VerifyLoginOTPResponse'
              type: object
        "400":
          description: Invalid request body or OTP verification failed
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Failed to create session
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Verify login OTP and create user session
      tags:
      - auth
  /auth/verify-register-otp:
    post:
      consumes:
      - application/json
      description: Verifies the OTP sent during registration and activates the user
        account
      parameters:
      - description: OTP verification request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.VerifyRegisterOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP verified and user activated successfully
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/schemas.VerifyRegisterOTPResponse'
              type: object
        "400":
          description: Invalid request body or OTP verification failed
          schema:
            $ref: '#/definitions/helper.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Verify registration OTP
      tags:
      - auth
  /protected/test:
    get:
      consumes:
      - application/json
      description: This endpoint tests the authentication middleware
      produces:
      - application/json
      responses:
        "200":
          description: Successfully authenticated
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Test protected endpoint
      tags:
      - Protected
swagger: "2.0"
